
#+title: Single Post with TOML front matter
#+author: donald lo
#+date: 2017-07-20

#+filetags: single toml cross-link @cat1 @cat2

#+hugo_base_dir: ../../
#+hugo_section: life
#+hugo_menu: :menu "foo" :weight 10 :parent main :identifier single-toml
#+description: Some description for this post.

This is a single post. You do not need to set the =EXPORT_FILE_NAME=
property in here. But then you also lose the tag and property
inheritance Org awesomeness.
你的生活1
* First heading in this post
This is a under first heading.
* Second heading in this post
This is a under second heading.
* Cross-linking
All of the below linked Org files *have to have* exported posts using
the /per-file/ flow, and they *cannot be* page bundles or have set a
different =#+export_file_name= --- See =ox-hugo= Issue #[[https://github.com/kaushalmodi/ox-hugo/issues/131][131]] for
requirements for this basic cross-linking to work as expected.
** Link to file in the same directory
This file will export the front-matter in TOML (default). See
** Link + Description
front-matter]].
** Link to file in a different directory
** Link to file that has a Hugo slug set
This one is magic! You can link to the Org file, no matter what slug
is set in the exported file.. Hugo will do the job of translating from
the Markdown file name to the actual link/slug.
afdjakjfksa

file

生活是什么


** Link to the CUSTOM_ID of a different file
* Local Variables                                         :ARCHIVE:noexport:
# Local Variables:
# org-link-file-path-type: relative
# End:
sdjfaskjf
